name: NormalDebugger
version: '1.0-SNAPSHOT'
main: org.normal.normalDebugger.NormalDebugger
api-version: '1.21'
load: STARTUP
commands:
  debuggui:
    description: Opens the event trace UI
    usage: /<command>
    permission: normaldebugger.debug
  toggleevent:
    description: Toggles a given event to be listened to
    usage: /<command>
    permission: normaldebugger.toggle